version: "3.9"
services:
  reiz:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - "edgedb"
  web:
    build:
        context: static/ui/
    ports:
      - "8080:8080"
    depends_on:
      - "reiz"
  edgedb:
    image: edgedb/edgedb:20210320022940b2b91d
    ports:
      - "5656:5656"
    volumes:
      - ./data:/var/lib/edgedb/data
    environment:
      - EDGEDB_PASSWORD=edgedb
