version: "3.8"
services:
  reiz:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - "edgedb"
  web:
    build:
        context: static/ui/
    ports:
      - "8080:8080"
    depends_on:
      - "reiz"
  edgedb:
    image: edgedb/edgedb:1-beta2
    ports:
      - "5656:5656"
    volumes:
      - ./data:/var/lib/edgedb/data
    environment:
      - EDGEDB_PASSWORD=edgedb
    logging:
        driver: none
