version: "2.4"
services:
  reiz:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - "edgedb"
  edgedb:
    image: edgedb/edgedb:1-beta2
    ports:
      - "5656:5656"
    volumes:
      - ./data:/var/lib/edgedb/data
    environment:
      - EDGEDB_PASSWORD=edgedb
    logging:
        driver: none
